"use client";

import { useMemo, useState } from "react";
import { personal, resume, site } from "@/data/portfolio";
import { type FitRow, fitSummary, interviewQuestions, matchRequirements } from "@/lib/fit";
import { beacon } from "@/lib/beacon";

/**
 * Paste a job description → requirement-by-requirement evidence from the
 * dossier, with honest gaps. Runs entirely in the browser: the JD is never
 * sent anywhere (only the strong/partial/gap counts are logged). The result
 * exports as a one-page brief a recruiter can forward.
 */

const BADGE: Record<FitRow["strength"], string> = {
  strong: "bg-accent text-paper",
  partial: "border border-accent text-accent",
  gap: "border border-rule text-ink-faint",
};

const SAMPLE = `Senior ML Engineer — LLM Platform
- Production ML systems in Python
- PyTorch and Hugging Face Transformers
- LLM inference serving: batching, KV cache, quantization
- Retrieval-augmented generation and vector databases
- LLM evaluation and guardrails against prompt injection
- Kubernetes for infrastructure`;

const titleOf = (jd: string) => jd.split("\n").map((l) => l.trim()).find(Boolean)?.slice(0, 80) ?? "the role";

/** A prefilled email to Divanshu: the recruiter sends it from their own client. */
function replyHref(rows: FitRow[], jd: string): string {
  const s = fitSummary(rows);
  const list = (k: FitRow["strength"]) =>
    rows
      .filter((r) => r.strength === k)
      .map((r) => `- ${r.requirement}`)
      .join("\n")
      .slice(0, 600);
  const body = [
    "Hi Divanshu,",
    "",
    `I ran the fit check on your portfolio against our role (${titleOf(jd)}): ${s.strong} strong, ${s.partial} partial, ${s.gap} gap.`,
    "",
    `Strong:\n${list("strong") || "-"}`,
    "",
    s.gap ? `Gaps we'd want to discuss:\n${list("gap")}` : "",
    "",
    "Would you be open to a conversation?",
    "",
  ].join("\n");
  return `mailto:${personal.email}?subject=${encodeURIComponent(`Role: ${titleOf(jd)}`)}&body=${encodeURIComponent(body)}`;
}

function brief(rows: FitRow[], jd: string): string {
  const s = fitSummary(rows);
  const title = titleOf(jd);
  const questions = interviewQuestions(rows);
  const lines = [
    `# ${personal.name} — fit against “${title}”`,
    "",
    `${personal.lead} · ${personal.currentRole} · ${personal.openTo}.`,
    "",
    `**${s.strong} strong · ${s.partial} partial · ${s.gap} gap** across ${s.total} requirements. Matched deterministically against his verified dossier (no model); gaps are reported, not stretched.`,
    "",
    "| Requirement | Match | Evidence |",
    "|---|---|---|",
    ...rows.map(
      (r) =>
        `| ${r.requirement.replace(/\|/g, "/")} | ${r.strength} | ${
          r.evidence.map((e) => `[${e.name}](${e.url})`).join(", ") || "—"
        } |`,
    ),
    "",
    ...(questions.length
      ? ["## Suggested deep-dive questions", "", ...questions.map((q) => `- ${q.q} (read first: ${q.url})`), ""]
      : []),
    `Contact: ${personal.email} · CV: ${site.url}/cv · Résumé: ${resume.href}`,
    `Generated by DIV-1 (${site.url}) on ${new Date().toISOString().slice(0, 10)}.`,
  ];
  return lines.join("\n");
}

export function FitPanel({ initial = "" }: { initial?: string }) {
  const [jd, setJd] = useState(initial);
  const [ran, setRan] = useState(initial ? initial : "");
  const [copied, setCopied] = useState(false);
  const rows = useMemo(() => (ran ? matchRequirements(ran) : []), [ran]);
  const s = fitSummary(rows);
  const questions = useMemo(() => interviewQuestions(rows), [rows]);

  const run = () => {
    setRan(jd);
    const r = matchRequirements(jd);
    const c = fitSummary(r);
    beacon("fit", { requirements: c.total, strong: c.strong, partial: c.partial, gap: c.gap });
  };

  const exportMd = (mode: "copy" | "download") => {
    const md = brief(rows, ran);
    beacon("brief", { mode, requirements: rows.length });
    if (mode === "copy") {
      navigator.clipboard?.writeText(md).then(() => {
        setCopied(true);
        setTimeout(() => setCopied(false), 1800);
      });
    } else {
      const a = document.createElement("a");
      a.href = URL.createObjectURL(new Blob([md], { type: "text/markdown" }));
      a.download = `divanshu-sharma-fit-${new Date().toISOString().slice(0, 10)}.md`;
      a.click();
      URL.revokeObjectURL(a.href);
    }
  };

  return (
    <div>
      <label htmlFor="fit-jd" className="font-mono text-[11px] tracking-[0.15em] text-ink-faint uppercase">
        Job description or requirements
      </label>
      <textarea
        id="fit-jd"
        value={jd}
        onChange={(e) => setJd(e.target.value)}
        rows={7}
        placeholder={"Paste the JD — one requirement per line works best.\n\nYour text stays in this browser."}
        className="mt-2 w-full resize-y border border-rule bg-surface px-3 py-2.5 font-mono text-[12px] leading-relaxed text-ink placeholder:text-ink-faint focus:border-accent focus:outline-none"
      />
      <div className="mt-2 flex flex-wrap items-center gap-3">
        <button
          type="button"
          onClick={run}
          disabled={!jd.trim()}
          className="border border-accent px-4 py-1.5 font-mono text-[11px] tracking-wider text-accent uppercase transition-colors hover:bg-accent hover:text-paper disabled:opacity-40"
        >
          match
        </button>
        {!jd ? (
          <button type="button" onClick={() => setJd(SAMPLE)} className="font-mono text-[11px] text-ink-faint underline underline-offset-2 hover:text-accent">
            try a sample JD
          </button>
        ) : null}
        <span className="font-mono text-[10px] text-ink-faint">matched in your browser · never sent · no model</span>
      </div>

      {rows.length ? (
        <div className="mt-6">
          <p className="font-mono text-[12px] text-ink" aria-live="polite">
            <span className="text-accent">{s.strong} strong</span> · {s.partial} partial · {s.gap} gap — {s.total} requirements
          </p>
          <ol className="mt-3 divide-y divide-rule-faint border-y border-rule-faint">
            {rows.map((r, i) => (
              <li key={`${i}-${r.requirement}`} className="grid gap-x-4 gap-y-1.5 py-3 sm:grid-cols-[72px_1fr]">
                <span className={`self-start px-1.5 py-0.5 text-center font-mono text-[10px] tracking-wide uppercase ${BADGE[r.strength]}`}>
                  {r.strength}
                </span>
                <div>
                  <p className="text-[14px] leading-snug text-ink">{r.requirement}</p>
                  {r.evidence.length ? (
                    <p className="mt-1 flex flex-wrap gap-x-3 gap-y-0.5 font-mono text-[11px]">
                      {r.evidence.map((e) => (
                        <a key={e.url + e.name} href={e.url} className="text-ink-muted underline decoration-rule underline-offset-2 hover:text-accent">
                          {e.name} ↗
                        </a>
                      ))}
                    </p>
                  ) : (
                    <p className="mt-1 font-mono text-[11px] text-ink-faint">nothing on record — reported, not stretched</p>
                  )}
                </div>
              </li>
            ))}
          </ol>
          {questions.length ? (
            <div className="mt-6">
              <p className="font-mono text-[11px] tracking-[0.15em] text-ink-faint uppercase">Interview prep — questions he&apos;s ready for</p>
              <ol className="mt-2 list-decimal space-y-1.5 pl-5 text-[14px] leading-snug text-ink-muted marker:font-mono marker:text-[11px] marker:text-accent">
                {questions.map((q) => (
                  <li key={q.q}>
                    {q.q}{" "}
                    <a href={q.url} className="font-mono text-[11px] text-ink-faint underline underline-offset-2 hover:text-accent">
                      read first ↗
                    </a>
                  </li>
                ))}
              </ol>
            </div>
          ) : null}
          <div className="mt-5 flex flex-wrap gap-3">
            <a
              href={replyHref(rows, ran)}
              onClick={() => beacon("contact", { via: "fit" })}
              className="border border-accent bg-accent px-3 py-1.5 font-mono text-[11px] text-paper hover:bg-transparent hover:text-accent"
            >
              email him about this role →
            </a>
            <button type="button" onClick={() => exportMd("copy")} className="border border-rule px-3 py-1.5 font-mono text-[11px] text-ink-muted hover:border-accent hover:text-accent">
              {copied ? "✓ brief copied" : "copy brief (markdown)"}
            </button>
            <button type="button" onClick={() => exportMd("download")} className="border border-rule px-3 py-1.5 font-mono text-[11px] text-ink-muted hover:border-accent hover:text-accent">
              download brief ↓
            </button>
          </div>
        </div>
      ) : null}
    </div>
  );
}
